### ISSUE TITLE
Project 2 (Sloan Holzman)

### ISSUE THREAD

**Issue by sloan-holzman** [ga-dc/project2-gallery#214]
Link to repo: https://git.generalassemb.ly/sloan-holzman/Project-2
Link to video: https://youtu.be/TZHBXiz-th0

note: I'll have to re-record the video...I didn't mention what I would have done differently or what I'd like to do next

**Comment by ZakkMan** [comment]
hey @sloan-holzman, I've added my feedback in a PR to your project 2 repo inside of a `feedback.md`: https://git.generalassemb.ly/sloan-holzman/Project-2/pull/1

Take a look and let me know if you have any questions. Really great job on your project!

One thing: You should move it from your Enterprise account to your normal GitHub account so that future employers can see it!
