### ISSUE TITLE
Project 2 - Ai Yen Tam

### ISSUE THREAD

**Issue by aiyentam** [ga-dc/project2-gallery#284]
**GitHub:** https://github.com/aiyentam/wedding_day
**Heroku** https://infinite-sierra-97558.herokuapp.com/
**YouTube:** https://www.youtube.com/watch?v=NkesZ9xv5mw

**Comment by ZakkMan** [comment]
# Project Evaluation

## Hard Requirements

The following must be true of your project for it to be considered complete:

- [x] The app is deployed to Heroku
- [x] A screencast is included in the submission
- [x] A new repo with the student's project is included in the submission

## Evaluation Requirements

Your scores on the following evaluation requirements are based on the [Evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project2/blob/master/evaluation.md) for this project. You must achieve at least a 1 (progressing) for each category. 

### Technical Requirements

> **Your Score: Excelling (3)**

You definitely meet all the hard requirements. It's really cool to see you also used Passport for authentication and multer for image uploads! Really great work on implementing both!

### Creativity & Interface

> **Your Score: Performing (2)**

Your interface is really great! I love the wedding photos. If you wanted to improve your score in this category consider things like: making it responsive or writing all the CSS yourself (instead of using Materialize). You could also make it so that galleries created by users present in the same way the gallery on the homepage does (as a slider). All in all, really great work!

### Code Quality

> **Your Score: Performing (2)**

Everything is well organized and well written. Really great job! In particular, I like the way you've organized your views (having an `auth/` folder in there, for instance) and the way you've structured your `index.js` and your controllers. As a tip, consider moving the loose functions in your Link controller out into a `utils/` directory to clean it up a little bit. Also consider the way you're naming things: Your Link controller is for uploading images and saving them to a gallery, perhaps Gallery would be a better name? 

### Functionality

> **Your Score: Excelling (3)**

Your application has quite a bit of functionality and it appears to mostly all be working! It looks like you've started building out a few additional features (like the Registry and Upcoming Events). Rather than have these throw a 404 error in your deployed version, work on those features on separate branches and only deploy them when they're finished. That said, it's really cool you got image uploads to work with multer and user authentication with passport! Those bring you up to a 3 🌟

### Planning / Process / Submission

> **Your Score: Progressing/Performing (1.5)**

You're close to a 2 here! I can see you started with a GitHub Project, but I don't see any other evidence of planning (like a wireframe or MVP, bronze, silver and gold versions). You also have a good start to your documentation in your readme but there are a couple more things we'd need to see for this to be a 2, which I list in the issue I posted on your repository. 


I've posted issues on your project repository with specific feedback and action items for you to consider. Your overall score on this project is 11.5. If you have any questions about my feedback, you can respond to that specific issue and I'll get back to you as soon as I can. I'm also happy to meet in person to discuss.

Great work!

**Comment by aiyentam** [comment]
Hi Zakk!

I have my wireframe and my mvp but I forgot to upload it :(
And I thought the comments will help make viewers read my code easier, but next time I will keep it out :)

I also thought you wanted to see how we would use materialized css >_< so I focus my css on materialized and hardcoded the css to change the color and height. But next time I will use my own :) (it’s also much easier too! Haha)

Thank you!
