### ISSUE TITLE
Project 2 Hannah Aurand

### ISSUE THREAD

**Issue by HannahAurand** [ga-dc/project2-gallery#286]
https://www.youtube.com/watch?v=w1aCSmOiYoM

https://github.com/HannahAurand/faithforward

**Comment by ZakkMan** [comment]
https://faithforward.herokuapp.com/

**Comment by ZakkMan** [comment]
# Project Evaluation

## Hard Requirements

The following must be true of your project for it to be considered complete:

- [x] The app is deployed to Heroku
- [x] A screencast is included in the submission
- [x] A new repo with the student's project is included in the submission

## Evaluation Requirements

Your scores on the following evaluation requirements are based on the [Evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project2/blob/master/evaluation.md) for this project. You must achieve at least a 1 (progressing) for each category. 

### Technical Requirements

> **Your Score: Performing (2)**

It looks like you have full CRUD on your model and you otherwise meet all the technical requirements! 👍 Really great work! To bring this to a 3, consider adding Authentication with Passport or maybe an event API like EventBrite or MeetUp.

### Creativity & Interface

> **Your Score: Performing (2)**

Your interface looks great - clean and simple. Consider spending some time building out your views, perhaps add a show page for your events?

### Code Quality

> **Your Score: Performing (2)**

Overall your code is well written. You're inconsistent about your css class names - that's not a big deal, but something to think about. In some cases, you use underscores, in others you camel case and in others you kebab case. I have always used kebab casing - you do you, so long as you're consistent.

### Functionality

> **Your Score: Performing (2)**

You've got a good amount of functionality here with no errors - great work!

### Planning / Process / Submission

> **Your Score: Performing (3)**

Great work on planning your project! I love the wireframes, your user stories are really well scoped, and it looks like you got through your MVP. Using GitHub projects is 👌

I've posted issues on your project repository with specific feedback and action items for you to consider. Your overall score on this project is [XXSCOREXX]. If you have any questions about my feedback, you can respond to that specific issue and I'll get back to you as soon as I can. I'm also happy to meet in person to discuss.

Great work!
