### ISSUE TITLE
Project 2 Qya Ahmad

### ISSUE THREAD

**Issue by rahmad239** [ga-dc/project2-gallery#287]
Hi,

Please see the links below: 
Github:
https://github.com/rahmad239/project_2
https://github.com/rahmad239/project_2.git
Video:
https://youtu.be/Rpf2nCTcPrw

**Comment by ZakkMan** [comment]
https://gotta-get-back.herokuapp.com/

**Comment by ZakkMan** [comment]
# Project Evaluation

## Hard Requirements

The following must be true of your project for it to be considered complete:

- [x] The app is deployed to Heroku
- [x] A screencast is included in the submission
- [x] A new repo with the student's project is included in the submission

## Evaluation Requirements

Your scores on the following evaluation requirements are based on the [Evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project2/blob/master/evaluation.md) for this project. You must achieve at least a 1 (progressing) for each category. 

### Technical Requirements

> **Your Score: Performing (2)**

You met all the technical requirements! 👍 To bring this up, consider adding passport or integrating with another API (like a map!). Otherwise, really great work!

### Creativity & Interface

> **Your Score: Performing (2)**

I'm really impressed you ventured into using materialize! Your interface looks great. Your wireframes are all really well done and your interface translates from them well. Materialize has a lot of more advanced features you could explore, like putting your forms in a container, adding additional details to your list of locations, etc. Exploring and implementing those would be a good way to bring this to the next level.

### Code Quality

> **Your Score: Performing (2)**

The quality of your code here is great! The only feedback I can offer is really minor: make sure your HTML is semantic, you're naming things well, be careful about how you organize things like imports. 

### Functionality

> **Your Score: Progressing/Performing (1.5)**

You've got full CRUD on your resource and everything works without errors. To bring this up to a 2, consider expanding your model or adding a second model. You could add other information about the places people are visiting, like a description, what time of year they went, or where they stayed. You could also make it so that places (St. John, Montezuma, etc) is one model and trips is another so you can track every user's trips to different locations. Another thing that would bring you to a 2 would be to add Users and authentication so users can track their own trips and maybe explore other users' trips. 

### Planning / Process / Submission

> **Your Score: Progressing/Performing (1.5)**

Your wireframes all look really great! I'm giving you a 1.5 because you have a good start to your planning process. For instance, it looks like you started using GitHub Projects for your user stories but didn't stick with it as you worked on your project (all your user stories are still listed under to do). You are also missing a readme for the repository, which is really important! Your planning document (`planning/readme.md`) is a good start for your repository readme. I *strongly* encourage you to write out a readme, per the issue I posted on your repo.

I've posted issues on your project repository with specific feedback and action items for you to consider. Your overall score on this project is 9. If you have any questions about my feedback, you can respond to that specific issue and I'll get back to you as soon as I can. I'm also happy to meet in person to discuss.

Great work!
