### ISSUE TITLE
Proj2 (Nhi Nguyen)

### ISSUE THREAD

**Issue by nnguy152** [ga-dc/project2-gallery#294]
Youtube: https://www.youtube.com/watch?v=KvaIHhSmgqE
GitHub: https://github.com/nnguy152/02-Con-A-Thon
Deployed: https://con-a-thon.herokuapp.com/conventions

**Comment by ZakkMan** [comment]
# Project Evaluation

## Hard Requirements

The following must be true of your project for it to be considered complete:

- [ ] The app is deployed to Heroku
- [ ] A screencast is included in the submission
- [ ] A new repo with the student's project is included in the submission

## Evaluation Requirements

Your scores on the following evaluation requirements are based on the [Evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project2/blob/master/evaluation.md) for this project. You must achieve at least a 1 (progressing) for each category. 

### Technical Requirements

> **Your Score: Performing (3)**

You definitely meet the technical requirements. Including the maps and authentication push this to a 3. If you wanted to push this part further, you could consider integrating with EventBrite or Meetup, add in Authorization and user roles so convention organizers can create accounts and manage their conventions, or build of social functionality around conventions like users being able to message other users going to the same convention(s).

### Creativity & Interface

> **Your Score: Performing (3)**

I love the interface! The font is great, as are the icons and the gif in the top corner. I really like that you have the "show" view for conventions as a popup, that's a really cool take on it. Additionally, I like that you've sprinkled some small animations and micro-interactions throughout. I think your next challenge should be to make it responsive!

### Code Quality

> **Your Score: Performing (1.5)**

The code quality in your `index.js` and in your controller is good but I feel like I have to take away some points for using inline styles and having your css spread out throughout the application as well as not using semantic HTML in a lot of places. To bring this up to a 2, move all your CSS in to a stylesheet and think through the naming of your CSS classes (consider using [BEM](http://handlebarsjs.com/partials.html)). Also, run your code through an HTML validator and work through the errors you get back.

### Functionality

> **Your Score: Performing (2)**

You've got a lot of great functionality in here!


### Planning / Process / Submission

> **Your Score: Performing (2)**

Your planning for this project looks really great! Your user stories are all well scoped and your wireframe looks great. I posted an issue about your readme, you should definitely add to it so has more information about your project and instructions on setting it up locally. We ask students to do this so that it looks nice and polished when future potential employers take a look at it!

I've posted issues on your project repository with specific feedback and action items for you to consider. Your overall score on this project is [XXSCOREXX]. If you have any questions about my feedback, you can respond to that specific issue and I'll get back to you as soon as I can. I'm also happy to meet in person to discuss.

Great work!
